### ISSUE TITLE
你好，我的任务成功启动起来，但是还是有问题

### ISSUE THREAD

**Issue by ylighgh** [NewComer00/NJUST_CloudData#1]
readme一步一步执行没有报错
也成功启动起来
但是访问页面就是nginx503报错
请问该怎么解决呢

**Comment by ylighgh** [comment]
502错误

**Comment by NewComer00** [comment]
没及时回复很抱歉！请问能提供详细信息吗？
比如运行机器的内存/操作系统/python版本和nginx版本等。。。

**Comment by NewComer00** [comment]
nginx和程序的log会记录在logs目录下面，日志信息能帮到你吗

**Comment by LyferLu** [comment]
你好，我也遇到了相同的问题。测试后发现使用root账户执行就会502错误。换用普通用户就解决了问题

**Comment by NewComer00** [comment]
由于我们之前安装Python包等操作是在普通用户下进行的，./app_manager.sh请一样通过普通用户执行，不需要使用sudo ./app_manager.sh。使用sudo会找不到之前安装的Python包。
已经在README中注明😃
